version: '3'
services:
  greehouse-db:
    image: postgres:11.10
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD: i-love-plants
      POSTGRES_USER: greenhouse
      POSTGRES_DB: greenhouse
  greenhouse-api:
    restart: unless-stopped
    container_name: greenhouse-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "npx prisma db seed"
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    depends_on:
      - greehouse-db
