version: "3.9"
services:
  proxy:
    restart: unless-stopped
    container_name: green-proxy
    build:
      context: ./GreenProxy
      dockerfile: ./Dockerfile
    ports:
      - 6864:6864
  core:
    restart: unless-stopped
    container_name: green-core
    build:
      context: ./GreenCore
      dockerfile: ./Dockerfile
    environment:
      - PROXY_URL=http://192.168.0.96:6864/greenproxy
    depends_on:
      - proxy
    ports:
      - 4686:4686